spring:
  application:
    name: product-service     # Eureka에 등록되는 서비스 이름
  datasource:
    url: jdbc:mysql://localhost:3306/msa_exam
    username: root
    password: 1225
  jpa:
    hibernate:
      ddl-auto: update        # 필요에 따라 create, none, validate로 변경 가능
    show-sql: true            # 콘솔에 SQL 쿼리 출력
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 19093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0